#!/usr/bin/env bash
set -Eeuo pipefail

mysql=(mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}")

"${mysql[@]}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${HELPIFY_DB_DATABASE}\`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${MYDEALER_DB_DATABASE}\`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${HELPIFY_DB_USERNAME}'@'%'
  IDENTIFIED WITH mysql_native_password BY '${HELPIFY_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYDEALER_DB_USERNAME}'@'%'
  IDENTIFIED WITH mysql_native_password BY '${MYDEALER_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${HELPIFY_DB_DATABASE}\`.*
  TO '${HELPIFY_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON \`${MYDEALER_DB_DATABASE}\`.*
  TO '${MYDEALER_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
SQL
